ksss/urls.py
from django.conf.urls.defaults import patterns, include, url
from ksss.web import views 
from ksss.web import models
from django.contrib.auth.views import login, logout
from django.views.static import serve
from django.contrib import admin
from ksss.settings import MEDIA_ROOT, MEDIA_URL

admin.autodiscover()

urlpatterns = patterns('',
    (r'^home/$', views.home),
    (r'^home/new/$', views.edit_news),
    (r'^home/edit/(\d+)/$', views.edit_news),
    (r'^news/(\d+)/$', views.one_news),
    (r'^(langholmen)/$', views.camp),
    (r'^(lokholmen)/$', views.camps),
    (r'^([a-z]*)/news/(\d+)/$', views.one_campnews),
    (r'^inventory/new/$', views.method_splitter, {'GET': views.get_inventory, 'POST': views.post_inventory}),
    (r'^inventory/edit/(?P<id>\d+)/$', views.method_splitter, {'GET': views.get_inventory, 'POST': views.post_inventory}),
    (r'^([a-z]*)/inventory/(\d+)/$', views.inventory),
    (r'^([a-z]*)/building/$', views.camps, {'building': True}),
    (r'^base/$', views.base),
    (r'^boats/$', views.boats),
    (r'^boats/new/$', views.add_boat),
    (r'^boats/edit/(\d+)/$', views.edit_boat),
    (r'^boats/delete/(\d+)/$', views.delete, {'item': models.Boat}),
    (r'^boats/(\d+)/$', views.boat),
    (r'^([a-z]*)/boats/$', views.campboats),
    (r'^damage/new/$', views.damage),
    (r'^damage/edit/(\d+)/$', views.damage),
    (r'^damage/delete/(\d+)/$', views.delete, {'item': models.ReportedDamage}),
    (r'^new_damage/thanks/$', views.thanks),
    (r'^media/upload/$', views.method_splitter_upload, {'GET':views.get_upload, 'POST':views.post_upload}),
    (r'^media/$', views.view_media),
    (r'^%s/(?P<path>.*)/$' % MEDIA_URL, serve, {'document_root': MEDIA_ROOT}),
    (r'^accounts/login/$', login),
    (r'^accounts/logout/$', logout),
    # Examples:
    # url(r'^$', 'ksss.views.home', name='home'),
    # url(r'^ksss/', include('ksss.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

ksss/web/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Damage(models.Model):
    name = models.CharField(max_length=30)
    
    def __unicode__(self):
        return self.name

class Camp(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(max_length=40, blank=True)

    def __unicode__(self):
        return self.name

class BoatTypes(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Motors(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Boat(models.Model):
    name = models.CharField(max_length=30)
    boat_type = models.ForeignKey(BoatTypes)
    motor = models.ForeignKey(Motors)
    motor_hp = models.CharField(max_length=3, blank=True)
    bought = models.CharField(max_length=4, blank=True)
    service = models.CharField(max_length=4, blank=True)
    current_port = models.ForeignKey(Camp, related_name="current_port")
    home_port = models.ForeignKey(Camp, related_name="home_port")
    notes = models.TextField(blank=True)
    def __unicode__(self):
        return self.name

class ReportedDamage(models.Model):
    boat = models.ForeignKey(Boat)
    damage = models.ForeignKey(Damage)
    description = models.TextField()
    actions_taken = models.TextField(blank=True)
    actions_needed = models.TextField(blank=True)
    repaired = models.BooleanField()
    def __unicode__(self):
        return u'%s - %s' % (self.damage, self.description)

class News(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    posted = models.DateField()
    author = models.CharField(max_length=30)
    camp = models.ForeignKey(Camp)

    def __unicode__(self):
        return self.title

class InventoryType(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Building(models.Model):
    name = models.CharField(max_length=30)
    camp = models.ForeignKey(Camp)

    def __unicode__(self):
        return self.name

class Inventory(models.Model):
    name = models.CharField(max_length=30)
    type = models.ForeignKey(InventoryType)
    amount = models.IntegerField(blank=True, null=True)
    current_amount = models.IntegerField(blank=True, null=True)
    buy_date = models.DateField(blank=True, null=True)
    seller = models.CharField(max_length=30, blank=True)
    bought_by = models.CharField(max_length=30, blank=True)
    guarantee = models.CharField(max_length=30, blank=True)
    manual = models.CharField(max_length=30, blank=True)
    camp = models.ForeignKey(Camp)
    storage_place = models.ForeignKey(Building, blank=True, null=True)
    notes = models.TextField(blank=True)

    def __unicode__(self):
        return self.name

class Position(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Upload(models.Model):
    title = models.CharField(max_length=30)
    camp = models.ForeignKey(Camp)
    position = models.ForeignKey(Position)
    file = models.FileField(upload_to='.')

    def __unicode__(self):
        return self.title

ksss/templates/add.html
{% extends 'base.html' %}
{% block page_title %}Lägg till skada{% endblock %}

{% block content %}

    <form action="" method="post" {% block enctype %}{% endblock %}>
    {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit"  value="Submit">
    </form>

    <article class="add">
        <section>
            <h1>Formatering</h1>
            <p>För att formatera din text, använd följande:</p>
            <table>
                <tr>
                    <td><span class="tag">&lt;p&gt;</span></td><td><span class="tag">nytt stycke</span></td>
                </tr>
                <tr>
                    <td><span class="tag">&lt;br&gt;</span></td><td><span class="tag">ny rad</span></td>  
                </tr>
                <tr>
                    <td><span class="tag">&lt;h1&gt;</span></td><td><span class="tag">börja rubrik</span></td>
                </tr>
                <tr>
                    <td><span class="tag">&lt;/h1&gt;</span></td><td><span class="tag">avsluta rubrik</span></td>
                </tr>
                <tr>
                    <td><span class="tag">&lt;*&gt;</span></td><td><span class="tag">punkt i punktlista</span></td>
                </tr>
            </table>
            <p id="helpbox">Den här texten:</p>

            <textarea readonly="true" cols="30" rows="9">
<h1>Viktig nyhet</h1>
<p>Bojen är kaputt.
Vi måste vidta dessa åtgärder:
<*>Köp en boj
<*>Fäst bojen

<p>Det var allt.<br>
Tack och hej!
            </textarea>
            <p id="helpbox">Kommer se ut såhär:</p>
                
                <section id="helpbox">
                    <h1>Viktig nyhet</h1>
                    <p>Bojen är kaputt.
                    Vi måste vidta dessa åtgärder:
                    <ul>
                        <li>Köp en boj</li>
                        <li>Fäst bojen</li>
                    </ul>

                    <p>Det var allt.<br>
                    Tack och hej!
                </section> 

        </section>
    </article>
{% endblock %}

ksss/templates/add_damage_old.html
{% extends 'base.html' %}
{% block page_title %}Lägg till skada{% endblock %}

{% block content %}

{% if errors %}
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form action="/batar" method="post">
    <p>Båt <input type="text" name="boat"></p>
    <p>Skada <input type="text" name="damage"></p>
    <p>Detaljer (valfritt) <textarea name="details" rows="10" cols="50"></textarea></p>
    <input type="submit"  value="Submit">
</form>


{% endblock %}

ksss/templates/boat.html
{% extends 'base.html' %}
{% block page_title %}{{ boat.id }}{% endblock %}
{% block page_head %}
{% endblock %}
{% block content %}

<div id="content">
    <h2>Allmänt</h2>
    <article>
        <table>
            <tbody>
                <tr>
                    <td><span class="tag">Namn: {{ boat.name }}</span></td>
                    <td><span class="tag">Typ: {{ boat.boat_type }}</span></td>
                    <td><span class="tag">Motor: {{ boat.motor }}</span></td>
                    {% if boat.motor %}
                    <td><span class="tag">Motorstyrka: {{ boat.motor_hp }}</span></td> 
                    {% endif %}
                </tr>
                <tr>
                    <td><span class="tag">Köpt: {{ boat.bought }}</span></td>
                    <td><span class="tag">Service: {{ boat.service }} </span></td>
                    <td><span class="tag">Nuvarande hamn: {{ boat.current_location }}</span></td>
                    <td><span class="tag">Hemmahamn: {{ boat.home_port }}</span></td>
                </tr>
                    <td colspan="4"><span class="tag">Anteckningar: {{ boat.notes }}</span></td>
                </tr>
            </tbody>
        </table>
        <div id="edit_boat">
            <a href="/boats/delete/{{ boat.id }}" title="Ta bort båt"><img src="/static/img/red_x.gif"></a></td>
            <a href="/boats/edit/{{ boat.id }}" title="Redigera båt" class="awesome small blue">Edit</a>
        </div>
    </article>
    {% if current_damages %}
    <h2>Skador</h2>
        {% for damage in boat.reporteddamage_set.all %}
            {% if not damage.repaired %}
                <article>
                    <table>
                        <tbody>
                            <tr>
                                <td><span class="tag">Skada: {{ damage.damage }}</span></td>
                                <td><span class="tag">Beskrivning: {{ damage.description }}</span></td>
                            </tr>
                            <tr>
                                <td><span class="tag">Vidtagna åtgärder: {{ damage.actions_taken }}</span></td>
                                <td><span class="tag">Nödvändiga åtgärder: {{ damage.actions_needed }}</span></td>
                            </tr>
                        </tbody>
                    </table>
                    <div id="edit_boat">
                        <a href="/damage/delete/{{ damage.id }}" title="Ta bort skada"><img src="/static/img/red_x.gif"></a>
                        <a href="/damage/edit/{{ damage.id }}" title="Redigera skada" class="awesome small blue">Edit</a>
                    </div>
                </article>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if repaired_damages %}
    <h2>Reparerade Skador</h2>
        {% for damage in boat.reporteddamage_set.all %}
            {% if damage.repaired %}
                <article>
                    <table>
                        <tbody>
                            <tr>
                                <td><span class="tag">Skada: {{ damage.damage }}</span></td>
                                <td><span class="tag">Beskrivning: {{ damage.description }}</span></td>
                            </tr>
                            <tr>
                                <td><span class="tag">Vidtagna åtgärder: {{ damage.actions_taken }}</span></td>
                                <td><span class="tag">Nödvändiga åtgärder: {{ damage.actions_needed }}</span></td>
                            </tr>
                        </tbody>
                    </table>
                    <div id="edit_boat">
                        <a href="/damage/delete/{{ damage.id }}" title="Ta bort skada"><img src="/static/img/red_x.gif"></a>
                        <a href="/damage/edit/{{ damage.id }}" title="Redigera skada" class="awesome small blue">Edit</a>
                    </div>
                </article>
            {% endif %}
        {% endfor %}
    {% endif %}

</div>





{% endblock %}

ksss/templates/boats.html
{% extends 'base.html' %}
{% block page_title %}Båtar{% endblock %}
{% block page_head %}
{% endblock %}
{% block content %}

<table id="myTable" class="tablesorter">
<thead>
    <tr>
        <th><b> Namn </b></th>
        <th><b> Typ </b> </th>
        <th><b> Hemmahamn </b> </th>
        <th><b> Skador </b></th>
    </tr>
</thead>
<tbody>
    {% for boat in Boats %}
        <tr>
            <td><a href="/boats/{{ boat.id }}" title="Visa båt">{{ boat.name }}</a>
                <a href="/boats/delete/{{ boat.id }}" title="Ta bort båt"><img src="/static/img/red_x.gif"></a></td>
            <td> {{ boat.boat_type }}</td>
            <td> {{ boat.home_port }} </td>
            {% if boat.reporteddamage_set.all %}
                <td>
                {% for damage in boat.reporteddamage_set.all %}
                    {% if not damage.repaired %}
                        <a href="/damage/edit/{{ damage.id }}" title="Redigera skada">{{ damage }}</a>
                    {% endif %}
                {% endfor %}
                </td>
            {% endif %}
        </tr>
    {% endfor %}
</tbody>
</table>

<script>
$(document).ready(function()
    {
        $("#myTable").tablesorter();
    }
);
</script>

<a href="/boats/new/" title="Ny båt" class="awesome medium blue">Ny båt</a>
<a href="/damage/new/" class="awesome medium blue" title="Ny skada">Ny skada</a>

{% block footer %}
<script type="text/javascript" src="/static/js/jquery.tablesorter.min.js"></script> 
{% endblock %}
{% endblock %}

ksss/templates/campnews.html
{% extends 'camps.html' %}

{% block sub_content %}
{% load markup %}

{% for newsitem in news|slice:":4" %}
    <article>

        <section> 
            <h1><a href="/news/{{ camp }}/{{ newsitem.id }}/">{{ newsitem.title }}</a></h1>
            <p> {{ newsitem.content|markdown }}
        </section>

        <footer>
            Posted on
            
            <datetime time="{{ newsitem.posted|date:"c" }}">

            <span>{{ newsitem.posted|date:"c" }}</span>

            </datetime>
                <div id="author">By {{ newsitem.author }}</div>

                <div id="edit_news">
                    <a href="/home/edit/{{ newsitem.id }}" title="Ändra nyhet" class="awesome medium grey">Edit</a>
                </div>
        </footer>

    </article>
{% endfor %}

    <a href="/home/new/" title="Ny nyhet" class="awesome medium grey">Ny nyhet</a>

{% endblock %}

ksss/templates/camps.html
{% extends "base.html" %}
{% block page_title %}{{ camp|capfirst }}{% endblock %}
{% block content %}

<div id="content">

<h1>{{ camp.name|capfirst }}</h1>
<aside class="news">
    <article id="newsmenu">
        <section>
            <h4><a href="/{{ camp.slug }}">Nyheter</a></h4>
                    {% for newsitem in news %}
                        {% if newsitem.camp|lower == camp %}
                            {% ifchanged %}
                            <h5>{{ newsitem.posted|date:"F" }}</h5>
                            {% endifchanged %}

                            <a href="/{{ camp.slug }}/news/{{ newsitem.id }}/">{{ newsitem.title }}</a>
                            {% if not forloop.last %}<br>{% endif %}
                        {% endif %}
                    {% endfor %}
            <h4><a href="/{{ camp.slug }}/inventory/0/">Inventarier</a></h4>
                        {% for item in inventorytype %}
                        <a href="/{{ camp.slug }}/inventory/{{ item.id }}">{{ item.name }}</a>
                            {% if not forloop.last %}<br>{% endif %}
                        {% endfor %}
            <h4>Byggnader</h4>
            <h4><a href="/{{ camp.slug }}/boats/">Båtar</a></h4>
            <h4>Läger</h4>
        </section>
    </article>
</aside>

{% block sub_content %}
{% endblock %}

{% block footer %}
    {% block sub_footer %}
    {% endblock %}
{% endblock %}
                
{% endblock %}

ksss/templates/home.html
{% extends "base.html" %}
{% block page_title %}Hem{% endblock %}
{% load markup %}
{% block content %}

<div id="content">

    <aside class="news">
        <article id="newsmenu">
            <section>
                <h3>Navigera nyheter</h3>
                    {% for newsitem in latest_news %}

                        {% ifchanged %}
                        <h4>{{ newsitem.posted|date:"F" }}</h4>
                        {% endifchanged %}

                    <a href="/news/{{ newsitem.id }}/">{{ newsitem.title }}</a>
                    
                        {% if not forloop.last %}<br>{% endif %}
                    {% endfor %}
            </section>
        </article>
    </aside>

    {% for newsitem in latest_news|slice:":4" %}

        <article>

            <section> 
                <h1><a href="/news/{{ newsitem.id }}/">{{ newsitem.title }}</a></h1>
                <p> {{ newsitem.content|markdown|slice:":300" }}
                {% if newsitem.content|length > 300 %}
                <p id="read_more"><em>Klicka på rubriken för att läsa vidare</em></p>
                {% endif %}
            </section>

            <footer>
                Posted on
                
                <datetime time="{{ newsitem.posted|date:"c" }}">

                <span>{{ newsitem.posted|date:"c" }}</span>

                </datetime>
                By {{ newsitem.author }}
                    <div id="edit_news">
                        <a href="/home/edit/{{ newsitem.id }}" title="Ändra nyhet" class="awesome medium grey">Edit</a>
                    </div>
            </footer>

        </article>

    {% endfor %}

    <a href="/home/new/" title="Ny nyhet" class="awesome medium grey">Ny nyhet</a>
</div>
            

{% endblock %}

ksss/templates/inventory.html
{% extends 'camps.html' %}

{% block sub_content %}


<table id="myTable" class="tablesorter">
<thead>
    <tr>
        <th><b> Namn </b></th>
        <th><b> Nuvarande antal </b> </th>
        <th><b> Så många ska finnas </b> </th>
    </tr>
</thead>
<tbody>
    {% for item in inventory %}
        {% if item.type == current_inventorytype and item.camp|lower == camp or current_inventorytype == 0 %}
        <tr>
            <td><a href="/inventory/edit/{{ item.id }}/">{{ item.name }}</a></td>
            <td> {{ item.current_amount }} </td>
            <td> {{ item.amount }} </td>
        </tr>
        {% endif %}
    {% endfor %}
</tbody>
</table>

<a href="/inventory/new/" title="Ny inventarie" class="awesome medium blue">Ny inventarie</a>

<script>
$(document).ready(function()
    {
        $("#myTable").tablesorter();
    }
);
</script>

{% endblock %}

{% block sub_footer %}
<script type="text/javascript" src="/static/js/jquery.tablesorter.min.js"></script> 
{% endblock %}

ksss/templates/langholmen.html
{% extends "base.html" %}
{% block page_title %}{{ camp|capfirst }}{% endblock %}
{% block content %}

<h1>{{ camp|capfirst }}</h1>
<aside>
    <article>
        <section>
            <ul>
                <li>Inventarier<li>
                    <ul>
                        {% for item in inventorytype %}
                        <li><a href="/inventory/{{ camp }}/item }}">{{ item }}</a></li>
                    </ul>
                <li>Byggnader</li>
                <li>Läger</li>
            </ul>
        </section>
    </article>
</aside>
                
{% endblock %}

ksss/templates/media.html
{% extends 'base.html' %}
{% block page_title %}
Media
{% endblock %}

{% block content %}

{% for media in media %}

    {{ media.title }}<br>

{% endfor %}
{% endblock %}

ksss/templates/news.html
{% extends 'base.html' %}
{% block page_title %}{{ newsitem.id }}{% endblock %}
{% load markup %}
{% block content %}

<div id="content">

    <aside class="news">
        <article id="newsmenu">
            <section>
                <h3>Navigera nyheter</h3>
                    {% for newsitem in latest_news %}

                        {% ifchanged %}
                        <h4>{{ newsitem.posted|date:"F" }}</h4>
                        {% endifchanged %}

                    <a href="/news/{{ newsitem.id }}/">{{ newsitem.title }}</a>
                    
                        {% if not forloop.last %}<br>{% endif %}
                    {% endfor %}
            </section>
        </article>
    </aside>

        <article>

            <section> 
                <h1><a href="/news/{{ newsitem.id }}/">{{ newsitem.title }}</a></h1>
                <p> {{ newsitem.content|markdown }}
            </section>

            <footer>
                Posted on
                
                <datetime time="{{ newsitem.posted|date:"c" }}">

                <span>{{ newsitem.posted|date:"c" }}</span>

                </datetime>
                    <div id="author">By {{ newsitem.author }}</div>

                    <div id="edit_news">
                        <a href="/home/edit/{{ newsitem.id }}" title="Ändra nyhet" class="awesome medium grey">Edit</a>
                    </div>
            </footer>

        </article>

</div>

{% endblock %}

ksss/templates/one_campnews.html
{% extends 'camps.html' %}

{% block sub_content %}
{% load markup %}
    <article>

        <section> 
            <h1>{{ current_news.title }}</h1>
            <p> {{ current_news.content|markdown }}
        </section>

        <footer>
            Posted on
            
            <datetime time="{{ current_news.posted|date:"c" }}">

            <span>{{ current_news.posted|date:"c" }}</span>

            </datetime>
                <div id="author">By {{ current_news.author }}</div>

                <div id="edit_news">
                    <a href="/home/edit/{{ current_news.id }}" title="Ändra nyhet" class="awesome medium grey">Edit</a>
                </div>
        </footer>

    </article>

{% endblock %}

ksss/templates/thanks.html
{% extends 'base.html' %}

{% block page_title %}Tack tack{% endblock %}

{% block content %}

<p> Tack

{% endblock %}

ksss/templates/upload.html
{% extends 'add.html' %}

{% block enctype %}
enctype="multipart/form-data"
{% endblock %}